version: '3.4'

services:
  server:
    image: nginx
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${APP_PORT}:80
    networks:
      - backend

  app:
    build: .docker/php
    image: php:7.2
    volumes:
      - ./:/var/www/html:rw
    networks:
      - backend

  mysql:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
